### ISSUE TITLE
Backspace and Delete are not working in Entity Editor text fields

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/save-game#2] opened 2022-09-14 14:52 UTC
On Windows, both keys are just ignored. On Linux, Backspace works properly, but Delete prints a `DEL` character.

**Comment by skejeton** [comment] 2022-09-18 08:24
Thank you for reporting windows related issues too, since I don't have access to that. Tophat's `getStr` doesn't work the same across platforms right now which is a Tophat issue, on linux it pushes backspace characters onto the character stream, but it doesn't do that on windows. Temporarily I'll fix this issue by checking if backspace was pressed.

**Comment by skejeton** [comment] 2022-09-18 08:25
Hold on, wait, I already use backspace check. I think the issue is then that Tophat doesn't emit backspace on windows. I'll take a look.

**Comment by vtereshkov** [comment] 2022-09-18 09:58
@skejeton Should I test anything on Windows?

**Comment by skejeton** [comment] 2022-09-18 14:40
@vtereshkov Do it now, marek fixed backspace

**Comment by skejeton** [comment] 2022-09-19 19:59
Closing this. It works now in Wine at least, aside from delete.

**Closed by skejeton** 2022-09-19 19:59 UTC
Labels: bug
